-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/linter (
  linter_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  linter_page INT UNSIGNED NOT NULL,
  linter_cat INT UNSIGNED NOT NULL,
  linter_start INT UNSIGNED NOT NULL,
  linter_end INT UNSIGNED NOT NULL,
  linter_params BLOB DEFAULT NULL,
  INDEX linter_page (linter_page),
  UNIQUE INDEX linter_cat_page_position (
    linter_cat, linter_page, linter_start,
    linter_end
  ),
  PRIMARY KEY(linter_id)
) /*$wgDBTableOptions*/;
